definitions:
  calculator.IPv4:
    properties:
      cidr:
        type: string
      count:
        type: integer
      end:
        type: string
      ip:
        type: string
      mask_bits:
        type: integer
      start:
        type: string
      subnet_mask:
        type: string
      wildcard_mask:
        type: string
    type: object
  calculator.IPv6:
    properties:
      long:
        $ref: '#/definitions/calculator.SubIPv6'
      short:
        $ref: '#/definitions/calculator.SubIPv6'
    type: object
  calculator.SubIPv6:
    properties:
      cidr:
        type: string
      count:
        type: integer
      end:
        type: string
      ip:
        type: string
      mask_bits:
        type: integer
      start:
        type: string
    type: object
  commonresp.Err:
    properties:
      detail:
        type: string
    type: object
  commonresp.Ok:
    type: object
  pixiv.Images:
    properties:
      img_urls:
        items:
          type: string
        type: array
    type: object
  userreq.User:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  userresp.Token:
    properties:
      token:
        type: string
    type: object
  userresp.User:
    properties:
      username:
        type: string
    type: object
info:
  contact: {}
  title: Neutron Star API
  version: "1.0"
paths:
  /calculator/ipv4:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: ip_addr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calculator.IPv4'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/commonresp.Err'
      summary: 解析 ipv4
      tags:
      - calculator
  /calculator/ipv6:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: ip_addr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calculator.IPv6'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/commonresp.Err'
      summary: 解析 ipv6
      tags:
      - calculator
  /pixiv:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: num
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pixiv.Images'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/commonresp.Err'
      summary: 获取 pixiv 图片 url
      tags:
      - pixiv
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userreq.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userresp.Token'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/commonresp.Err'
      summary: 登录
      tags:
      - user
  /user/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userresp.User'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/commonresp.Err'
      security:
      - ApiKeyAuth: []
      summary: 个人信息
      tags:
      - user
  /user/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/userreq.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/commonresp.Ok'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/commonresp.Err'
      summary: 注册
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
