definitions:
  calculator.IPv4:
    properties:
      cidr:
        type: string
      count:
        type: integer
      end:
        type: string
      ip:
        type: string
      mask_bits:
        type: integer
      start:
        type: string
      subnet_mask:
        type: string
      wildcard_mask:
        type: string
    type: object
  calculator.IPv6:
    properties:
      long:
        $ref: '#/definitions/calculator.SubIPv6'
      short:
        $ref: '#/definitions/calculator.SubIPv6'
    type: object
  calculator.SubIPv6:
    properties:
      cidr:
        type: string
      count:
        type: integer
      end:
        type: string
      ip:
        type: string
      mask_bits:
        type: integer
      start:
        type: string
    type: object
  model.Err:
    properties:
      detail:
        type: string
    type: object
  pixiv.ImageInDB:
    properties:
      create_time:
        type: string
      id:
        type: integer
      is_r18:
        type: boolean
      origin_url:
        type: string
      relative_path:
        type: string
      tags:
        type: string
    type: object
info:
  contact: {}
  title: Neutron Star API
  version: "1.0"
paths:
  /calculator/ipv4:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: ip_addr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calculator.IPv4'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Err'
      summary: 解析 ipv4
      tags:
      - calculator
  /calculator/ipv6:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: ip_addr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/calculator.IPv6'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Err'
      summary: 解析 ipv6
      tags:
      - calculator
  /pixiv:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: num
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pixiv.ImageInDB'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Err'
      summary: 获取 pixiv 图片 url
      tags:
      - pixiv
swagger: "2.0"
